_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.7.16
        t:
            "1":
                - 1
                - 51
                - 55
            "2":
                - 1
                - 51
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.7.16
            "5": 0.18.7
            "8":
                - 2
                - 5
            "12": 0.18.7
            "13": linux-x86_64
base_lr:
    value: 0.01
batch_size:
    value: 8
dataset:
    value: KiTS19
deterministic:
    value: 1
exp:
    value: TU_KiTS19_224
img_size:
    value: 224
list_dir:
    value: ./lists_kits19
max_epochs:
    value: 100
max_iterations:
    value: 30000
n_gpu:
    value: 1
n_skip:
    value: 3
num_classes:
    value: 3
root_path:
    value: kits19/data
seed:
    value: 1234
vit_name:
    value: R50-ViT-B_16
vit_patches_size:
    value: 16
