wandb_version: 1

root_path:
  desc: null
  value: kits19/data
list_dir:
  desc: null
  value: ./lists_kits19
dataset:
  desc: null
  value: KiTS19
num_classes:
  desc: null
  value: 3
max_iterations:
  desc: null
  value: 50000
max_epochs:
  desc: null
  value: 150
batch_size:
  desc: null
  value: 1
n_gpu:
  desc: null
  value: 1
deterministic:
  desc: null
  value: 1
base_lr:
  desc: null
  value: 0.01
img_size:
  desc: null
  value: 224
seed:
  desc: null
  value: 1234
n_skip:
  desc: null
  value: 3
vit_name:
  desc: null
  value: R50-ViT-B_16
vit_patches_size:
  desc: null
  value: 16
checkpoint_dir:
  desc: null
  value: ./checkpoints_kits1
use_attention:
  desc: null
  value: 1
exp:
  desc: null
  value: TU_KiTS19_224
_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.17.7
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1734523852
    t:
      1:
      - 1
      - 51
      - 55
      - 105
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 105
      3:
      - 13
      - 16
      - 23
      4: 3.10.9
      5: 0.17.7
      8:
      - 2
      - 5
      13: linux-x86_64
